language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - pip uninstall numpy -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq cython python-numpy python-scipy
install:
  - pip install pep8 pyflakes
  - pip install -e .
  - pip freeze
script:
  - pep8 --repeat setup.py distributions
  - pyflakes setup.py distributions
  - nosetests -v
  - ./test_cmake.sh
cache:
  apt: true
  directories:
    - $HOME/virtualenv/python2.7_with_system_site_packages/lib/python2.7/site-packages
